  import java.util.*;
      
   class A {
	   
	private int a = 10; 
	
	 void add () {
			
		int ab = 100;
		int cd = 200;
		new B().display(ab,cd);
	}
	
	class B {
		
		void display(int ab,int cd) {
			
		System.out.println ( a);
		System.out.println ( ab);
		System.out.println ( cd); 
		 }
	  }
   }
   
   public class PineApple {
   
     public static void main ( String [] args ) {
	 
	     A ob = new A ();
		 A.B obj = ob.new B(); 
		 obj.display(10,20);
	 
	  }
	 
   }
   
   
   
   
   
   /*          🧠 Key Points

.java → source code (you write it)

.class → bytecode (generated by compiler)

JVM executes the bytecode

Java is platform independent because of bytecode */